In [1]:
import duckdb
import polars as pl
pl.Config.set_tbl_rows(60)

import pandas as pd

import shutil

In [2]:
data_path = '/media/dm/1TB/Data Fusion Contest 2026/task1/'
ver = "40"

In [3]:
conn = duckdb.connect('my_duckdb_database.db')

customer_id – id клиента банка
event_id — id операции
event_dttm – дата/время операции
event_type_nm – тип операции
event_desc – закодировнное описание операции
channel_indicator_type – канал совершения операции
channel_indicator_subtype – подтип канала совершения операции
operaton_amt — сумма операции в рублях
currency_iso_cd – валюта операции
mcc_code – группа MCC merchant_category_code
pos_cd – закодированное значение point of sale condition code
accept_language – язык заголовка http запроса
browser_language – язык браузера
timezone — часовой пояс
session_id – идентификатор сессии
operating_system_type – закодированное значение операционной системы
battery – заряд устройства
device_system_version – версия операционной системы
screen_size – разрешение экрана
developer_tools — настройки разработчика (флаг на устройстве)
phone_voip_call_state – флаг события VoIP-звонка во время проведения операции
web_rdp_connection – флаг наличия удаленного управления над устройством
compromised – наличие Root-доступа на устройстве

# Получение данных

In [4]:
%%time
#Консолидация данных с очисткой pretest.parquet от дублей

#если в планах нет использования порядка строк, оставить закомментированными строки с --file 

data = conn.sql(f"""
    SELECT * FROM
        (SELECT *, True AS pre, True AS train 
            FROM read_parquet([ '{data_path}pretrain_part_1.parquet',
                                '{data_path}pretrain_part_2.parquet',
                                '{data_path}pretrain_part_3.parquet'
                                ]
                            --file_row_number=True, filename=True 
                            )
        UNION ALL
        SELECT *, False AS pre, True AS train 
            FROM read_parquet([ '{data_path}train_part_1.parquet',
                                '{data_path}train_part_2.parquet',
                                '{data_path}train_part_3.parquet'
                                ]
                            --file_row_number=True, filename=True
                            )
        UNION ALL
        SELECT DISTINCT *, True AS pre, False AS train --удаление дублей в pretest.parquet
            FROM read_parquet('{data_path}pretest.parquet'
                                    --file_row_number=True, filename=True 
                                    ) 
                ANTI JOIN '{data_path}test.parquet' USING (event_id) --удаление пересечений с test.parquet
        UNION ALL
        SELECT *, False AS pre, False AS train 
            FROM read_parquet('{data_path}test.parquet'
                                --,file_row_number=True, filename=True
                                )
        ) ORDER BY event_dttm, event_id
        """)
#data.shape
#shape: (191_310_789, 27)
#(191310790, 25)
conn.sql(f"""
    DESCRIBE data
        """).df()

CPU times: user 27.7 ms, sys: 3.76 ms, total: 31.4 ms
Wall time: 29.5 ms

                   column_name column_type null   key default extra
0                  customer_id      BIGINT  YES  None    None  None
1                     event_id      BIGINT  YES  None    None  None
2                   event_dttm     VARCHAR  YES  None    None  None
3                event_type_nm     INTEGER  YES  None    None  None
4                   event_desc     INTEGER  YES  None    None  None
5       channel_indicator_type     INTEGER  YES  None    None  None
6   channel_indicator_sub_type     INTEGER  YES  None    None  None
7                 operaton_amt      DOUBLE  YES  None    None  None
8              currency_iso_cd     INTEGER  YES  None    None  None
9                     mcc_code     VARCHAR  YES  None    None  None
10                      pos_cd     INTEGER  YES  None    None  None
11             accept_language     VARCHAR  YES  None    None  None
12            browser_language     VARCHAR  YES  None    None  None
13                    timezone     INTEGER  YES  None    None  None
14                  session_id      BIGINT  YES  None    None  None
15       operating_system_type     INTEGER  YES  None    None  None
16                     battery     VARCHAR  YES  None    None  None
17       device_system_version     VARCHAR  YES  None    None  None
18                 screen_size     VARCHAR  YES  None    None  None
19             developer_tools     VARCHAR  YES  None    None  None
20       phone_voip_call_state     INTEGER  YES  None    None  None
21          web_rdp_connection     INTEGER  YES  None    None  None
22                 compromised     VARCHAR  YES  None    None  None
23                         pre     BOOLEAN  YES  None    None  None
24                       train     BOOLEAN  YES  None    None  None

In [5]:
%%time
#Типизация

#HASH используется если само значение неважно, но хочется подсчитывать использование этого значения ранее 
data = conn.sql(f"""
        SELECT 
            customer_id,  
            event_id,  
            event_dttm::TIMESTAMP AS event_dttm,
            --event_dttm::TIME AS time, -- лучше вычислять позже
            extract('hour' FROM event_dttm::TIMESTAMP)::UINT8 AS hour,
            ((extract('hour' FROM event_dttm::TIMESTAMP)+0)//2%12)::UINT8 AS hour2_0,
            ((extract('hour' FROM event_dttm::TIMESTAMP)+1)//2%12)::UINT8 AS hour2_1,
            
            event_type_nm::TINYINT AS event_type_nm,
            event_desc::SMALLINT AS event_desc,
            
            channel_indicator_type::TINYINT AS channel_indicator_type,
            channel_indicator_sub_type::TINYINT AS channel_indicator_sub_type,
            
            operaton_amt::FLOAT AS operaton_amt,
            
            COALESCE( currency_iso_cd, -1)::TINYINT AS currency_iso_cd,
            COALESCE( mcc_code, '-1')::TINYINT AS mcc_code,
            COALESCE( pos_cd, -1)::TINYINT AS pos_cd,
            
            (hash(COALESCE( accept_language,'-') )%(256*256-1))::UINT16 AS accept_language,--
            (hash(COALESCE( browser_language,'-') )%(256*256-1))::UINT16 AS browser_language,
            COALESCE( timezone, -1)::INT AS timezone,
            (session_id IS NULL) AS session_id_NULL,
            COALESCE( session_id, row_number() OVER (ORDER BY event_dttm, event_id) ) AS session_id,
            COALESCE( operating_system_type, 99)::TINYINT AS operating_system_type,
            --(battery IS NULL) AS battery,
            (hash(COALESCE( device_system_version,'-') )%(256*256-1))::UINT16 AS device_system_version,
            (hash(COALESCE( screen_size,'-') )%(256*256-1))::UINT16 AS screen_size,
            COALESCE( developer_tools,'9')::TINYINT AS developer_tools,
            COALESCE( phone_voip_call_state,'9')::TINYINT AS phone_voip_call_state,
            COALESCE( web_rdp_connection,'9')::TINYINT AS web_rdp_connection,
            COALESCE( compromised,'9')::TINYINT AS compromised,
            ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY event_dttm, event_id)::UINT16 AS CUST_ROW_NUMBER,
            pre,
            train,
            --file_row_number,
            --filename,
        FROM data
        ORDER BY customer_id, event_dttm, event_id
        """)

conn.sql(f"""
    DESCRIBE data
        """).df()

CPU times: user 33.7 ms, sys: 4.81 ms, total: 38.5 ms
Wall time: 34.4 ms

                   column_name column_type null   key default extra
0                  customer_id      BIGINT  YES  None    None  None
1                     event_id      BIGINT  YES  None    None  None
2                   event_dttm   TIMESTAMP  YES  None    None  None
3                         hour    UTINYINT  YES  None    None  None
4                      hour2_0    UTINYINT  YES  None    None  None
5                      hour2_1    UTINYINT  YES  None    None  None
6                event_type_nm     TINYINT  YES  None    None  None
7                   event_desc    SMALLINT  YES  None    None  None
8       channel_indicator_type     TINYINT  YES  None    None  None
9   channel_indicator_sub_type     TINYINT  YES  None    None  None
10                operaton_amt       FLOAT  YES  None    None  None
11             currency_iso_cd     TINYINT  YES  None    None  None
12                    mcc_code     TINYINT  YES  None    None  None
13                      pos_cd     TINYINT  YES  None    None  None
14             accept_language   USMALLINT  YES  None    None  None
15            browser_language   USMALLINT  YES  None    None  None
16                    timezone     INTEGER  YES  None    None  None
17             session_id_NULL     BOOLEAN  YES  None    None  None
18                  session_id      BIGINT  YES  None    None  None
19       operating_system_type     TINYINT  YES  None    None  None
20       device_system_version   USMALLINT  YES  None    None  None
21                 screen_size   USMALLINT  YES  None    None  None
22             developer_tools     TINYINT  YES  None    None  None
23       phone_voip_call_state     TINYINT  YES  None    None  None
24          web_rdp_connection     TINYINT  YES  None    None  None
25                 compromised     TINYINT  YES  None    None  None
26             CUST_ROW_NUMBER   USMALLINT  YES  None    None  None
27                         pre     BOOLEAN  YES  None    None  None
28                       train     BOOLEAN  YES  None    None  None

In [6]:
%%time
# запись консолидированного и типизированного в parquet
data.write_parquet(f'data{ver}.pq')
#Wall time: 9min 1s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 48min 42s, sys: 7min 1s, total: 55min 43s
Wall time: 10min 42s

# просмотр parquet методами duckdb и polars

In [7]:
%%time
# просмотр данных методами duckdb и polars

#conn.sql(f""" SELECT * FROM read_parquet(f'data{ver}.pq') LIMIT 5 """).show()
#conn.sql(f""" SELECT * FROM read_parquet(f'data{ver}.pq') LIMIT 5 """).df()
pl.scan_parquet(f'data{ver}.pq').head().collect()
#pl.read_parquet(f'data{ver}.pq').head()

CPU times: user 111 ms, sys: 60.5 ms, total: 172 ms
Wall time: 188 ms

shape: (5, 29)
┌──────────────┬──────────────┬──────────────┬──────┬───┬─────────────┬─────────────┬──────┬───────┐
│ customer_id  ┆ event_id     ┆ event_dttm   ┆ hour ┆ … ┆ compromised ┆ CUST_ROW_NU ┆ pre  ┆ train │
│ ---          ┆ ---          ┆ ---          ┆ ---  ┆   ┆ ---         ┆ MBER        ┆ ---  ┆ ---   │
│ i64          ┆ i64          ┆ datetime[μs] ┆ u8   ┆   ┆ i8          ┆ ---         ┆ bool ┆ bool  │
│              ┆              ┆              ┆      ┆   ┆             ┆ u16         ┆      ┆       │
╞══════════════╪══════════════╪══════════════╪══════╪═══╪═════════════╪═════════════╪══════╪═══════╡
│ 123123123123 ┆ 123251972261 ┆ 2023-10-01   ┆ 9    ┆ … ┆ 9           ┆ 1           ┆ true ┆ true  │
│ 129          ┆ 925          ┆ 09:16:41     ┆      ┆   ┆             ┆             ┆      ┆       │
│ 123123123123 ┆ 125193298164 ┆ 2023-10-01   ┆ 11   ┆ … ┆ 9           ┆ 2           ┆ true ┆ true  │
│ 129          ┆ 858          ┆ 11:13:48     ┆      ┆   ┆             ┆             ┆      ┆       │
│ 123123123123 ┆ 124823932244 ┆ 2023-10-01   ┆ 11   ┆ … ┆ 9           ┆ 3           ┆ true ┆ true  │
│ 129          ┆ 729          ┆ 11:40:35     ┆      ┆   ┆             ┆             ┆      ┆       │
│ 123123123123 ┆ 124454563399 ┆ 2023-10-01   ┆ 16   ┆ … ┆ 9           ┆ 4           ┆ true ┆ true  │
│ 129          ┆ 321          ┆ 16:37:32     ┆      ┆   ┆             ┆             ┆      ┆       │
│ 123123123123 ┆ 126490377886 ┆ 2023-10-02   ┆ 19   ┆ … ┆ 9           ┆ 5           ┆ true ┆ true  │
│ 129          ┆ 229          ┆ 19:28:25     ┆      ┆   ┆             ┆             ┆      ┆       │
└──────────────┴──────────────┴──────────────┴──────┴───┴─────────────┴─────────────┴──────┴───────┘

# Примеры вычисления признаков

In [12]:
%%time
field = 'event_desc'

query_str=f"""
    SELECT *,

            --разница в секундах с предыдущей записью в рамках customer_id
            COALESCE( epoch(event_dttm - (LAG(event_dttm) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW))),-1)::INT32 AS LAG_CUST,            

            --АГРЕГАЦИИ в разрезе customer_id
            --количество записей ранее текущей записи в рамках customer_id
            COUNT(*) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS COUNT_BEFORE,            
            
            --количество записей с заполненым operaton_amt ранее текущей записи в рамках customer_id 
            COUNT(operaton_amt) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN  UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS SCOUNT_BEFORE,            
            
            --количество уникальных значений field ранее текущей записи в рамках customer_id
            --COUNT(DISTINCT {field}) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS UNIQUE_{field},            

            --сумма operaton_amt записей ранее текущей записи в рамках customer_id
            SUM(operaton_amt) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS SUM_BEFORE,            
            
            --среднее operaton_amt записей ранее текущей записи в рамках customer_id
            MEAN(operaton_amt) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MEAN_BEFORE,            
            
            --медиана operaton_amt записей ранее текущей записи в рамках customer_id
            MEDIAN(operaton_amt) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MEDIAN_BEFORE,            
            
            --максимум operaton_amt записей ранее текущей записи в рамках customer_id
            MAX(operaton_amt) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MAX_BEFORE,            
            
            --максимум operaton_amt без 5% выбросов записей ранее текущей записи в рамках customer_id
            QUANTILE_CONT(operaton_amt, 0.95) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)::FLOAT AS MAX095_BEFORE,   


            --ПЕРИОДЫ
            --количество записей за последний час исключая текущую запись в рамках customer_id
            COUNT(*) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN INTERVAL 1 HOUR PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS COUNT_1H_,            

            --количество записей за последний час включая текущую запись в рамках customer_id
            COUNT(*) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN INTERVAL 1 HOUR PRECEDING AND CURRENT ROW)::INT AS COUNT_1H,            

            --количество записей до последнего часа в рамках customer_id
            COUNT(*) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND INTERVAL 1 HOUR PRECEDING)::INT AS COUNT_BEFORE_1H,            

            --количество записей за месяц до последнего часа в рамках customer_id
            COUNT(*) OVER (PARTITION BY customer_id ORDER BY event_dttm RANGE BETWEEN INTERVAL 1 MONTH PRECEDING AND INTERVAL 1 HOUR PRECEDING)::INT AS COUNT_1M_1H,



            --ИМЕНОВАННЫЕ ОКНА
            MEDIAN(operaton_amt) OVER w_2M_1D::FLOAT AS MEDIAN_2M_1D,            
            SUM(operaton_amt) OVER w_2M_1D::FLOAT AS SUM_2M_1D,            
            QUANTILE_CONT(operaton_amt, 0.95) OVER w_2M_1D::FLOAT AS MAX095_2M_1D,            
            
            (
                (operaton_amt - AVG(operaton_amt) OVER w_2M_1D 
                )/stddev_samp(operaton_amt) OVER w_2M_1D 
            )::FLOAT AS ZScore_2M_1D,   



            -- в разрезе customer_id и field
            --разница в секундах с предыдущей записью в рамках customer_id и field
            COALESCE( epoch(event_dttm - (LAG(event_dttm) OVER (PARTITION BY customer_id, {field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW))),-1)::INT32 AS LAG_{field},            
            
            --количество записей с таким же значением field ранее текущей записи в рамках customer_id и field
            COUNT(*) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS COUNT_{field},            
            
            --количество записей с таким же значением field  с заполненым operaton_amt ранее текущей записи в рамках customer_id и field
            COUNT(operaton_amt) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::INT AS SCOUNT_{field},            

            --доля записей с таким же значением field ранее текущей записи в рамках customer_id
            (COUNT(*) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW))/CUST_ROW_NUMBER::FLOAT AS FRAC_{field},            
            
            --смягченная доля записей с таким же значением field ранее текущей записи в рамках customer_id и field
            (COUNT(*) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW))/(CUST_ROW_NUMBER+4)::FLOAT AS FRAC_{field},            


            --сумма operaton_amt записей с таким же значением field ранее текущей записи в рамках customer_id и field
            SUM(operaton_amt) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS SUM_{field},            

            --среднее operaton_amt записей с таким же значением field ранее текущей записи в рамках customer_id и field
            AVG(operaton_amt) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS AVG_{field},            

            --максиум operaton_amt записей с таким же значением field ранее текущей записи в рамках customer_id и field
            MAX(operaton_amt) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MAX_{field},            

            --медиана operaton_amt записей с таким же значением field ранее текущей записи в рамках customer_id и field
            MEDIAN(operaton_amt) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MEDIAN_{field},            

            --максимум operaton_amt без 5% выбросов записей с таким же значением field ранее текущей записи в рамках customer_id и field
            QUANTILE_CONT(operaton_amt, 0.95) OVER (PARTITION BY customer_id,{field} ORDER BY event_dttm RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)::FLOAT AS MAX095_{field},            
            
            
    FROM read_parquet('data{ver}.pq')
    
    WINDOW w_2M_1D AS (PARTITION BY customer_id 
                        ORDER BY event_dttm 
                        RANGE BETWEEN INTERVAL 2 MONTH PRECEDING AND INTERVAL 1 DAY PRECEDING)
            
        """
#print(query_str)
data = conn.sql(query_str)  
data.write_parquet(f'data{ver}a.pq')
#Wall time: 19min 55s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 2h 25min 51s, sys: 2min 9s, total: 2h 28min
Wall time: 19min 55s

In [13]:
%%time
pl.scan_parquet(f'data{ver}a.pq').filter(pl.col("operaton_amt").is_not_null()).head(20).collect()

CPU times: user 38.7 s, sys: 3.05 s, total: 41.8 s
Wall time: 5.9 s

shape: (20, 55)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ event_id   ┆ event_dttm ┆ hour ┆ … ┆ AVG_event_ ┆ MAX_event ┆ MEDIAN_ev ┆ MAX095_ev │
│ d          ┆ ---        ┆ ---        ┆ ---  ┆   ┆ desc       ┆ _desc     ┆ ent_desc  ┆ ent_desc  │
│ ---        ┆ i64        ┆ datetime[μ ┆ u8   ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆            ┆ s]         ┆      ┆   ┆ f32        ┆ f32       ┆ f32       ┆ f32       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1235526198 ┆ 1264130690 ┆ 2023-11-21 ┆ 15   ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 55103      ┆ 32651      ┆ 15:52:27   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1240680190 ┆ 2024-03-01 ┆ 8    ┆ … ┆ 422226.0   ┆ 422226.0  ┆ 422226.0  ┆ 422226.0  │
│ 55103      ┆ 62004      ┆ 08:20:57   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1237587816 ┆ 2024-03-01 ┆ 8    ┆ … ┆ 6.555214e6 ┆ 1.2688202 ┆ 6.555214e ┆ 1.2074903 │
│ 55103      ┆ 13185      ┆ 08:58:08   ┆      ┆   ┆            ┆ e7        ┆ 6         ┆ e7        │
│ 1235526198 ┆ 1241968692 ┆ 2025-06-25 ┆ 16   ┆ … ┆ 7022942.5  ┆ 1.2688202 ┆ 7.9584e6  ┆ 1.2215222 │
│ 55103      ┆ 48995      ┆ 16:26:07   ┆      ┆   ┆            ┆ e7        ┆           ┆ e7        │
│ 1235526198 ┆ 1251159900 ┆ 2023-10-02 ┆ 6    ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 55152      ┆ 40372      ┆ 06:31:15   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1253822765 ┆ 2023-10-02 ┆ 4    ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 55551      ┆ 29914      ┆ 04:21:12   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1246091828 ┆ 2023-10-09 ┆ 7    ┆ … ┆ 29697.0    ┆ 29697.0   ┆ 29697.0   ┆ 29697.0   │
│ 55551      ┆ 21537      ┆ 07:24:24   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1261553710 ┆ 2023-10-10 ┆ 11   ┆ … ┆ 34720.5    ┆ 39744.0   ┆ 34720.5   ┆ 39241.648 │
│ 55551      ┆ 36065      ┆ 11:24:39   ┆      ┆   ┆            ┆           ┆           ┆ 438       │
│ 1235526198 ┆ 1232433856 ┆ 2023-10-11 ┆ 15   ┆ … ┆ 36431.0    ┆ 39852.0   ┆ 39744.0   ┆ 39841.199 │
│ 55551      ┆ 59526      ┆ 15:21:37   ┆      ┆   ┆            ┆           ┆           ┆ 219       │
│ 1235526198 ┆ 1251417594 ┆ 2023-10-12 ┆ 19   ┆ … ┆ 37313.25   ┆ 39960.0   ┆ 39798.0   ┆ 39943.800 │
│ 55551      ┆ 73333      ┆ 19:23:23   ┆      ┆   ┆            ┆           ┆           ┆ 781       │
│ 1235526198 ┆ 1263615298 ┆ 2023-10-13 ┆ 23   ┆ … ┆ 37869.8007 ┆ 40096.0   ┆ 39852.0   ┆ 40068.800 │
│ 55551      ┆ 11572      ┆ 23:22:47   ┆      ┆   ┆ 81         ┆           ┆           ┆ 781       │
│ 1235526198 ┆ 1257602373 ┆ 2023-10-15 ┆ 3    ┆ … ┆ 38287.5    ┆ 40376.0   ┆ 39906.0   ┆ 40306.0   │
│ 55551      ┆ 72122      ┆ 03:22:58   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1255884348 ┆ 2023-10-16 ┆ 7    ┆ … ┆ 38500.1445 ┆ 40376.0   ┆ 39852.0   ┆ 40292.0   │
│ 55551      ┆ 01339      ┆ 07:23:01   ┆      ┆   ┆ 31         ┆           ┆           ┆           │
│ 1235526198 ┆ 1235612111 ┆ 2023-10-17 ┆ 11   ┆ … ┆ 38686.625  ┆ 40376.0   ┆ 39906.0   ┆ 40278.0   │
│ 55551      ┆ 33042      ┆ 11:21:44   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1240078878 ┆ 2023-10-18 ┆ 15   ┆ … ┆ 38805.0    ┆ 40376.0   ┆ 39852.0   ┆ 40264.0   │
│ 55551      ┆ 44062      ┆ 15:22:08   ┆      ┆   ┆            ┆           ┆           ┆           │
│ 1235526198 ┆ 1245404643 ┆ 2023-10-19 ┆ 19   ┆ … ┆ 38935.3007 ┆ 40376.0   ┆ 39906.0   ┆ 40255.398 │
│ 55551      ┆ 33937      ┆ 19:24:37   ┆      ┆   ┆ 81         ┆           ┆           ┆ 438       │
│ 1235526198 ┆ 1254767654 ┆ 2023-10-20 ┆ 23   ┆ … ┆ 39016.4531 ┆ 40376.0   ┆ 39852.0   ┆ 40242.0   │
│ 55551      ┆ 41162      ┆ 23:21:11   ┆      ┆   ┆ 25         ┆           ┆           ┆           │
│ 1235526198 ┆ 1242054585 ┆ 2023-10-22 ┆ 3    ┆ … ┆ 39070.4179 ┆ 40376.0   ┆ 39840.0   ┆ 40228.601 │
│ 55551      ┆ 31662      ┆ 03:22:43   ┆      ┆   ┆ 69         ┆           ┆           ┆ 562       │
│ 1235526198 ┆ 1261124219 ┆ 2023-10-23 ┆ 7    ┆ … ┆ 39136.6914 ┆ 40376.0   ┆ 39852.0   ┆ 40215.199 │
│ 55551      ┆ 04549      ┆ 07:25:48   ┆      ┆   ┆ 06         ┆           ┆           ┆ 219       │
│ 1235526198 ┆ 1260866544 ┆ 2023-10-24 ┆ 11   ┆ … ┆ 39194.3554 ┆ 40376.0   ┆ 39892.0   ┆ 40201.800 │
│ 55551      ┆ 87931      ┆ 11:24:11   ┆      ┆   ┆ 69         ┆           ┆           ┆ 781       │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴───────────┴───────────┴───────────┘

# Создание файлов TRAIN и TEST

In [16]:
%%time
#(наклейка меток из train_labels.parquet)
data = conn.sql(f"""
    SELECT 
            * EXCLUDE (target),
            (target IS NOT NULL)::BOOLEAN as label,
            COALESCE( target, 0)::BOOLEAN AS target
    FROM (SELECT 
            * EXCLUDE (pre, train),
        FROM read_parquet('data{ver}a.pq') 
        WHERE train AND NOT pre
    ) LEFT JOIN read_parquet('{data_path}train_labels.parquet') AS lbl USING (customer_id,event_id)
""")
data.write_parquet(f"train{ver}.pq")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 5min 6s, sys: 21.1 s, total: 5min 27s
Wall time: 45.2 s

In [19]:
%%time
data = conn.sql(f"""
        SELECT 
            * EXCLUDE (pre, train),
        FROM read_parquet('data{ver}a.pq') 
        WHERE NOT train AND NOT pre
""")
data.write_parquet("test{ver}.pq")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

CPU times: user 1min 19s, sys: 6.73 s, total: 1min 25s
Wall time: 12.5 s